### ISSUE TITLE
Love the project, think I found an issue

### ISSUE THREAD

**Issue by revixter** [AK-Saigyouji/Procedural-Cave-Generator#1]
Not sure if you'll get the same results as I did, but I cannot get a cave to generate outside of the editor on Windows.
I started a new unity project, created an empty object and attached the cave generator script to it. I attached another script that simply calls caveGenerator.Generate() on Input.GetMouseButtonDown(0).  Works exactly as intended in the editor or when built for the Android. Does nothing at all when built for Windows.

**Comment by AK-Saigyouji** [comment]
I managed to reproduce the same issue. Checking the logs, it seems an error occurs in MeshTangent.dll, though it's quite bizarre that it does not occur in the editor, nor in an Android build. MeshTangents.dll was quite a bit out of date - I swapped in the most recent MeshTangentCalculator from my other repo and the issue went away. The fix has been pushed to the current build.

Thanks for opening the issue, this was a nasty error to have lurking in the project.
