### ISSUE TITLE
Problem creating prefab

### ISSUE THREAD

**Issue by camta005** [AK-Saigyouji/Procedural-Cave-Generator#2]
Hi, great work on the project.

I can get the release version 1.0 working, but the latest build is not working for me on Windows 8.1. I can build the cave successfully with 'generate new map', but when I use 'create prefab' I get this error:

InvalidOperationException: Prefab creation failed, unexpected cave hierarchy: sector child with no mesh.
CaveGeneratorEditor.ExtractMesh (UnityEngine.Transform component) (at Assets/Editor/CaveGeneratorEditor.cs:154)
CaveGeneratorEditor.CreateMeshAsset (UnityEngine.Transform component, System.String path) (at Assets/Editor/CaveGeneratorEditor.cs:131)
CaveGeneratorEditor.CreateMeshAssets (UnityEngine.Transform cave, System.String path) (at Assets/Editor/CaveGeneratorEditor.cs:115)
CaveGeneratorEditor.CreatePrefab (UnityEngine.GameObject cave) (at Assets/Editor/CaveGeneratorEditor.cs:89)
UnityEditor.DockArea:OnGUI()

**Comment by AK-Saigyouji** [comment]
Thanks for reporting this, it seems I broke prefab creation when I recently revamped the cave generator. I'll add an automated test to my build process so this kind of error doesn't make it to a live build in the future.
